/pal_laser_filters:
  use_preset: "range_filter_w_non_circular_footprint.yaml"
  use_if:
    base_type: omni_base
  ros__parameters:
    filter2:
      params:
        footprint: "[[0.35, 0.24], [-0.35, 0.24], [-0.35, -0.24], [0.35, -0.24]]"