/rgbd_camera:
  use_preset: "d435i_rgbd_low_contrast.yaml"
  use_if:
    robot_type: omni_base
    camera_model: realsense-d435i
    add_on_module: horizon
  ros__parameters:
    camera_name: "rgbd_camera"
    serial_no: "${serial_number_camera_0}"